### ISSUE TITLE
[Feature Request] Disable partial message output & Global tab list suggestions

### ISSUE THREAD

**Issue by ghost** [Team-Jackdaw/Essential-PlayerInfo#5]
### 1. Disable partial message output
If you remove some language messages in the config file, like this

![image](https://user-images.githubusercontent.com/68630033/159147105-4d36ad20-60c9-4c37-b9bd-61077cc5dee5.png)

no language message is filled in, the output is automatically disabled
(In the current version, If is not filled in here, it will output blank information [empty column])

### 2. Global tab list suggestions
Customize the display prefix of other server players or provide the option to close it directly
Player display styles on other servers are no longer the spectator mode style

By the way, this plugin is really awesome, thanks author

###### Note: I use machine translation because I don't understand English

**Comment by WDRshadow** [comment]
Yes, thank you for your suggestion. I will change and add these features in the next version. @Lokeyli

**Comment by WDRshadow** [comment]
很抱歉让你等这么久，我们在新版本里面加入了你提到的功能。https://github.com/Team-Jackdaw/Essential-PlayerInfo/pull/10
你可以在[Releases](https://github.com/Team-Jackdaw/Essential-PlayerInfo/releases)中下载。

**Comment by Lokeyli** [comment]
属于是语言模块崩坏了，机翻味浓过谷歌生草机
