### ISSUE TITLE
Toggled messages displaying globally

### ISSUE THREAD

**Issue by rockit7** [Team-Jackdaw/Essential-PlayerInfo#6]
I have a velocity server with global chat. When staff do /staffmsg on to toggle on the staff chat it is sharing the chat in the other servers. But, it doesn't happen when they do /staffmsg MESSAGE only. This is the same with /partychat on. When they do the command then the message it doesn't send globally, but only sends when its toggled on for persistent chat.

**Comment by WDRshadow** [comment]
Thank you. I will take care of it. This plugin is now only focus on broadcast the massage which is sent from players client instead of other plugins. But I will try to adapt it to a wider situations soon.
