### ISSUE TITLE
建议增加RedisBungee-Velocity支持,以及重新在papermc的新论坛发布资源

### ISSUE THREAD

**Issue by Illusionika** [Team-Jackdaw/Essential-PlayerInfo#7]
看了一眼 开发者是中国人,能直接写中文了,真好

这个插件真的挺好用的,一个插件解决三个问题.直到我迫于形势不得不拆成2个群组
现在RedisBungee的最新8.0开发版已经支持Velocity了.求支持
RedisBungee开发版在actions里,Github地址:
https://github.com/ProxioDev/RedisBungee

还有旧的Velocity论坛被爆破了.现在已经论坛迁移到paper那边去了 ,建议重新发布下
https://forums.papermc.io/forums/velocity-plugin-releases/

**Comment by QingXia-Ela** [comment]
@Illusionika  两位主要开发人员都在准备考研找学校，消息我会进行转达的

**Comment by Illusionika** [comment]
https://modrinth.com/

发现个新的资源站,插件可以发布在这类,有专门的velocity分类

**Comment by WDRshadow** [comment]
感谢你的推荐，我们已经在新论坛上发布这个插件。关于适配RedisBungee，并不是十分清楚这个插件的用途，带深入了解后我们会进行尝试。
