### ISSUE TITLE
在1.19.1和以上版本使用会出现问题

### ISSUE THREAD

**Issue by Illusionika** [Team-Jackdaw/Essential-PlayerInfo#8]
?这插件有人更新了?

好像是Velocty对于1.19.1的聊天签名没有支持还是怎么的 (从别的聊天插件看到的 https://github.com/WiIIiam278/HuskChat/issues/72)

-------------

这个插件现在只要子服只要高于1.19.1就会一人聊天全服被踢,不确定是哪个模块出现了问题.我用其他插件做了下实验:

用这个只有跨服聊天功能的插件不会出现被踢现象
https://github.com/FeuSalamander/Vmessage

但是一加上这个tablist插件就和你的插件现象一样了,一人说话全服被踢
https://github.com/OskarsMC-Plugins/tablist

-----------------

补充一下,我的环境是Velocty前端+Fabric后端

**Comment by WDRshadow** [comment]
新年好！

关于1.19.1的通讯验证问题，推荐的做法是在server.properties中关闭enable-secure-profile。

本来想在这寒假跟进一下之前的issue和新的feature，但另一个开发者的电脑在旅游的时候丢了，进展有点缓慢(＞人＜;)

**Comment by WDRshadow** [comment]
高版本的聊天签名应该不影响该插件的使用，目前为止在正式版的Velocity（3.1.1）还没有对此做适应性的调整，我会一直关注这个问题，因为他也影响到我们团队自己的服务器了。但在server.properties中关闭enable-secure-profile后可以缓解这个问题。

**Comment by Illusionika** [comment]
我enable-secure-profile是关闭的,我也不确定到底是插件的哪个模块出了问题,但是可以确定是1.19.1更新时候出了问题, 跑1.18.2没问题.有空我弄个测试环境一个个模块单独试试
(我之前那时候是3.1.2-SNAPSHOT现在官方更新了3.2.0-SNAPSHOT还没试这个组合,上次出问题之后把我吓得滚回1.18.2了)

**Comment by Illusionika** [comment]
怪了.我把插件的所有模块都enabled=false还是会出问题. 说话者本人提示"聊天消息验证失败"然后被踢,其他人也直接一起被踢

测试环境和下载地址如下

-----------------------
Velocity方面:
https://api.papermc.io/v2/projects/velocity/versions/3.2.0-SNAPSHOT/builds/216/downloads/velocity-3.2.0-SNAPSHOT-216.jar
插件部分:
https://github.com/Team-Jackdaw/Essential-PlayerInfo/releases/download/v2.0.0/Essential-Playerinfo-Plugin-2.0.1.jar
https://cdn.modrinth.com/data/pYyGVpcC/versions/KjBi9LCR/OwoVelocityPlugin.jar

配置文件改动以下几个地方:
force-key-authentication = false
player-info-forwarding-mode = "modern"
announce-forge = true
ping-passthrough = "mods"

----------------------
服务端和客户端方面:
用的这个1.19.2整合包,测试版本是[v4.4.5],要怎么装的有写介绍
https://modrinth.com/modpack/create-origin 

然后服务器上额外安装这几个mod
https://cdn.modrinth.com/data/8dI2tmqs/versions/v2.3.0/FabricProxy-Lite-2.3.0.jar
https://cdn.modrinth.com/data/YkOyn1Pn/versions/0.1.5/crossstitch-0.1.5.jar

server.properties的enforce-secure-profile=false
config配置文件里
FabricProxy-Lite.toml要填上Velocity的密钥
origins_server.json 里第一行的 "performVersionCheck": false

客户端用启动器下载整合包再额外安装个crossstitch-0.1.5.jar就行了

------------------------
Fabric服只要话就会被踢
高版本的bukkit则不会出事(我用的purpur,并且开了kick-for-out-of-order-chat: false,可能正好解决了这个问题,不然也会因为out-of-order-chat被踢)

**Comment by WDRshadow** [comment]
你好，这其实不是插件的问题，是1.19.1更新聊天消息验证造成的问题。我可以给你提供一下解决思路：
1. 在高版本服务器的`server.properties`中关闭`enable-secure-profile`。
2. 你也许使用了authlib-injector.jar或者YggdrasilOfficialProxy.jar，请确保所有高版本的服务器中也加载该验证插件，即使你的服务器中`online-mode=false`，来确保该服务器采用与Velocity相同的方式验证玩家消息。
3. 你也许是用了高版本的Velocity（3.1.2或以上），高版本的proxy有对消息验证功能进行适配但仍是快照版，新接口的doc仍不完善，你可以退回到3.1.1或以下版本来缓解该问题。（我们插件的[v3.1.0快照](https://github.com/Team-Jackdaw/Essential-PlayerInfo/releases)只适用于3.1.2以上版本）
